# Generated by Django 2.2.3 on 2019-08-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190807_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='hunter',
            new_name='username',
        ),
    ]
